languageCode = "en-us"
title = "Rootless Containers"
baseurl = "https://rootlesscontaine.rs/"
theme = "base16"
publishDir = "../docs"
enableemoji = true

[params]
	Author = "Aleksa Sarai"

# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
[markup.goldmark.renderer]
  unsafe= true
